name: 'Fast FTP'
description: 'Syncs files via FTP/SFTP to a remote server'
inputs:
  server:
    description: 'FTP server name (you may need to specify a port)'
    required: true
  username:
    description: 'FTP account username'
    required: true
  password:
    description: 'FTP account password'
    required: true
  method:
    description: 'Protocol used to deploy (ftp or sftp)'
    required: false
    default: "ftp"
  port:
    description: 'The port used to connect to the server'
    required: false
    default: "21"
  local_dir:
    description: 'The local folder to copy, defaults to root project folder'
    required: false
    default: ""
  remote_dir:
    description: 'The remote folder to copy to, deafults to root FTP folder'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.server }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.method }}
    - ${{ inputs.port }}
    - ${{ inputs.local_dir }}
    - ${{ inputs.remote_dir }}
branding:
  icon: 'upload-cloud'
  color: 'blue'
